### PR TITLE
Macro based IntoDatum for string types

### PR DESCRIPTION
**Pull request by YohDeadfall**
The pull request follows two goals:
* don't repeat yourself,
* implement `IntoDatum` for `&CString` to mirror implementation of the trait for `&String`.

### CODE REVIEW

**Comment by YohDeadfall** [comment]
@workingjubilee, I need your opinion on that since I would like to have that in my pull request switch to `Datum<'mcx>` and adjust less code during rebase.

**Comment by workingjubilee** [comment]
on which?

**Comment by YohDeadfall** [comment]
I meant this whole pull request. The thing is that my other unpublished change touches all `IntoDatum` implementations, so I would like to clean up the current code first, have less work later, and avoid potential rebase too.

**Comment by workingjubilee** [comment]
@YohDeadfall Would it work to implement the CStr variations on `Deref<Target = CStr>`?

**Comment by YohDeadfall** [comment]
Yes, that was my first thought, but at the same time a custom type might use that `T` which is `Deref<CStr>` too. That can end up in conflicts, and that's my concern.

**Comment by workingjubilee** [comment]
Hmm.

**Comment by workingjubilee** [comment]
Eh, okay. This is as we currently have and we can make the deref-based change later if we want.

**Pull request merged**
