### PR TITLE
Made SPI query arguments type safe

### PR DESCRIPTION
**Pull request by YohDeadfall**

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
`&[][..]` is not something you see every day.  Why is it that `&[]` doesn't work?

**Comment by YohDeadfall** [comment]
I guess it's leftover from the time when I tried to play with generics and avoid a breaking change. That was required by the compiler for the type deduction, but can be reduced now.

**Comment by eeeebbbbrrrr** [comment]
I appreciate your efforts on this area of pgrx, btw. 

Spi is incredibly hard to get right in C, and it’s not any easier in Rust.

**Review by eeeebbbbrrrr — APPROVED** [review]
This is **really** nice, @YohDeadfall.  Really nice.

Very clean.

Like @workingjubilee said somewhere, I think we'd want to hold this for v0.13, but I think this PR is a motivator for getting there quickly.

**Comment by workingjubilee** [comment]
@YohDeadfall Can you resolve the conflicts?

**Comment by YohDeadfall** [comment]
Sure! Actually, I just wanted to write you about this pull request too (:

**Review by workingjubilee — APPROVED** [review]
Thanks!

**Pull request merged**
