### PR TITLE
pg17beta2 support

### PR DESCRIPTION
**Pull request by eeeebbbbrrrr**
Starting on pg17beta2 support...

Some tests fail locally.  I dunno if these passed before -- I didn't run the test suite first.  I assume they didn't.  Will investigate.

Not sure what'll happen on CI, which is why I'm PRing this now:

```
test tests::proptests::tests::pg_date_literal_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_timetz_literal_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_timestamp_literal_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_time_literal_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_date_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_timetz_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_time_spi_roundtrip ... FAILED
test tests::proptests::tests::pg_timestamp_spi_roundtrip ... FAILED
```

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
interesting.  Those tests also fail for me locally from `develop` using pg16.  What's up with that?  Any idea @workingjubilee?

They all have the same failure pattern:

```
Postgres Messages:
[2024-07-27 11:58:23.173 EDT] [1608822] [66a5191f.188c76]: LOG:  starting PostgreSQL 16.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
[2024-07-27 11:58:23.173 EDT] [1608822] [66a5191f.188c76]: LOG:  listening on IPv4 address "127.0.0.1", port 32216
[2024-07-27 11:58:23.175 EDT] [1608822] [66a5191f.188c76]: LOG:  listening on Unix socket "/home/zombodb/_work/pgrx/target/test-pgdata/.s.PGSQL.32216"
[2024-07-27 11:58:23.181 EDT] [1608822] [66a5191f.188c76]: LOG:  database system is ready to accept connections


Test Function Messages:
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: LOG:  statement: BEGIN
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: LOG:  statement: SELECT "tests"."date_spi_roundtrip"();
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: ERROR:  function tests.date_spi_roundtrip() does not exist at character 8
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: STATEMENT:  SELECT "tests"."date_spi_roundtrip"();
[2024-07-27 11:58:23.467 EDT] [1611050] [66a5191f.18952a]: LOG:  statement: ROLLBACK


Client Error:
function tests.date_spi_roundtrip() does not exist
postgres location: parse_func.c
rust location: <unknown>
```

I'm running `cargo test --all --features pg16,cshim --no-default-features` from the root of the repo.  Am I missing something?

**Comment by eeeebbbbrrrr** [comment]
> Am I missing something?

YES!  I was missing the `proptest` feature.  Okay.  Something to look at later...

**Comment by eeeebbbbrrrr** [comment]
tests pass locally now on both linux and MacOS.  A+++

I'm doing the CI dance now to get it to install/use the 17 beta deb packages.

**Comment by eeeebbbbrrrr** [comment]
As far as I can tell, this is ready to merge

**Comment by workingjubilee** [comment]
@eeeebbbbrrrr This needs a rebase.

**Comment by eeeebbbbrrrr** [comment]
done

**Comment by workingjubilee** [comment]
oh nice.

**Review by workingjubilee — COMMENTED** [review]
thank you!

**Pull request merged**
