### PR TITLE
feat: add `ForeignDataWrapperRelationId` OID definitions

### PR DESCRIPTION
**Pull request by burmecia**
This PR is to add `ForeignDataWrapperRelationId` OID definitions, on par with `ForeignServerRelationId` and `ForeignTableRelationId`.

PostgreSQL source code ref:

- pg12: https://github.com/postgres/postgres/blob/REL_12_STABLE/src/include/catalog/pg_foreign_data_wrapper.h
- pg13: https://github.com/postgres/postgres/blob/REL_13_STABLE/src/include/catalog/pg_foreign_data_wrapper.h
- pg14: https://github.com/postgres/postgres/blob/REL_14_STABLE/src/include/catalog/pg_foreign_data_wrapper.h
- pg15: https://github.com/postgres/postgres/blob/REL_15_STABLE/src/include/catalog/pg_foreign_data_wrapper.h
- pg16: https://github.com/postgres/postgres/blob/REL_16_STABLE/src/include/catalog/pg_foreign_data_wrapper.h

### CODE REVIEW

**Comment by burmecia** [comment]
The test failure looks like not related to this PR.

**Comment by eeeebbbbrrrr** [comment]
This PR is wrong.  :)

The files you modified are actually machine generated, based on processing of the [`pgrx-pg-sys/include/`](https://github.com/pgcentralfoundation/pgrx/tree/develop/pgrx-pg-sys/include).  The files in git are not actually used by pgrx.

What you need to do is add the proper set of Postgres headers into those files and PR that.

I know it's unusual to have machine-generated code committed into a repo, but these files need to exist only to appease docs.rs.

> The test failure looks like not related to this PR.

It's not.  We'll handle that separately.

**Comment by burmecia** [comment]
Thanks for that info, I updated the PR and it looks good now.

**Comment by eeeebbbbrrrr** [comment]
Great!  Thanks!

I'll merge this now.  It might be January before we publish another release.  It kinda depends on our vacation schedules this month and what other changes we see come in over the next week or two.

**Pull request merged**
