### PR TITLE
Organize bindgen arg sets in fn (nfc)

### PR DESCRIPTION
**Pull request by workingjubilee**
No functional changes.

### CODE REVIEW

**Review by thomcc — COMMENTED** [review]
I'm not sure that this is an improvement honestly. Why is it a trait?

**Comment by workingjubilee** [comment]
> I'm not sure that this is an improvement honestly. Why is it a trait?

for mostly-preserving the existing method call syntax, thassit. happy to make them free fn.

**Comment by thomcc** [comment]
I'd prefer free functions, since then adding parameters and such doesn't require modifying as many places.

**Comment by workingjubilee** [comment]
sounds good to me!

**Comment by thomcc** [comment]
We talked about this on discord and I don't really care about this enough to object to it becoming a trait if that's a change @workingjubilee wants to make.

**Comment by workingjubilee** [comment]
Free fn are fine. We discussed some options for improving things further and like... mostly, I'm okay with anything as long as it's somewhat more organized than "not at all". The main goal is to avoid this becoming impossible to read and sift through when more bindgen flags get added.

**Pull request merged**
