### PR TITLE
Include varlena functions

### PR DESCRIPTION
**Pull request by daamien**
There's already a pgrx::varlena module but this header brings utility fonctions to manipulate GUC variables and identifiers.

### CODE REVIEW

**Comment by workingjubilee** [comment]
> pgrx::varlena

To clarify, most of that cannot actually be defined via bindgen, because bindgen does not "do" function macros.

@daamien Please find and include the additional headers for varlenas like varatt.h, and explicitly include them even if they are transitively included already.

**Comment by workingjubilee** [comment]
Note that varatt.h is a recent split-off header so this will actually differ from version to version.

**Comment by daamien** [comment]
Hi @workingjubilee 

I don't see any macros in the varlena header file... Am I missing something ?

I can add `varatt.h` for PG16. Should I also add `utils/sortsupport.h` ?

**Comment by workingjubilee** [comment]
Apologies, the comment about macros was only related in my own head, I think.

> Should I also add utils/sortsupport.h?

Sure.

**Comment by workingjubilee** [comment]
Thank you!

**Pull request merged**
