### PR TITLE
u32 has bad diagnostics with `#[pg_extern]`

### PR DESCRIPTION
**Pull request by workingjubilee**
Check in a test that demonstrates this so that we are aware of improvements, and to prevent any regressions, as they used to be significantly worse.

This is a step towards resolving these issues:
- https://github.com/pgcentralfoundation/pgrx/issues/951
- https://github.com/pgcentralfoundation/pgrx/issues/1536

### CODE REVIEW

**Comment by workingjubilee** [comment]
@nyurik This is a bit indirect still, isn't it? The spans are all fucked up.

**Comment by nyurik** [comment]
Thx for working on it!  But yeah, trait not satisfied error is a bit of a rabbit hole...  Perhaps it might be better to handle it explicitly?  I am sure there will be plenty of surprises for such a common use case of an incorrect data type - so juts look at the input/return params in the `PgExtern::new` or nearby, and raise an error?

**Comment by workingjubilee** [comment]
nondet diagnostic output, adding cshim alters the hash I think

**Comment by workingjubilee** [comment]
> Thx for working on it! But yeah, trait not satisfied error is a bit of a rabbit hole... Perhaps it might be better to handle it explicitly? I am sure there will be plenty of surprises for such a common use case of an incorrect data type - so juts look at the input/return params in the PgExtern::new or nearby, and raise an error?

Well, I'd rather not special-case the strings of any types (at least, any further than our code already does...), because given the sheer amount of FFI pgrx involves, people are very likely to do something like:

```rust
#[pg_extern]
fn pg_fn(arg: ffi::c_uint) -> ffi::c_ulong {
```

**Comment by workingjubilee** [comment]
This is not to say I'm against adding more diagnostic code here, I'd just rather do so in a more underhanded / generic way, like e.g. emitting structs with the name of the error I would want to emit and embedding the argument and return types in the struct.

**Comment by workingjubilee** [comment]
Nope, last one didn't fix it. Guess I'm waiting for better test infra or finding a way to emit a better diagnostic or rustc being less random about ordering here.

**Comment by nyurik** [comment]
How about just handle the well known simple types, e.g. `u16`, `u32`, ...?

**Comment by workingjubilee** [comment]
> How about just handle the well known simple types, e.g. `u16`, `u32`, ...?

It feels like it lacks a satisfactory boundary.

**Comment by nyurik** [comment]
Well, it is not perfect, i agree, but if it will make the most common usecase more helpful... at least maybe give a warning?

**Comment by workingjubilee** [comment]
> Well, it is not perfect, i agree,

It isn't about perfection. The problem in this case is that there are three type systems involved (Rust's, C's, and Postgres's), and people are going to have different opinions about what is "obvious" and "common". Without usage statistics (and `cargo pgrx` doesn't include telemetry), I can't rule anything out.

**Comment by workingjubilee** [comment]
I'm going to do some things that will significantly affect the diagnostics and might make them significantly worse or better, so this PR needs to serve its original purpose.

**Comment by nyurik** [comment]
Would the recently released diagnostics support help in this case?  https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#diagnostic-attributes

**Pull request closed without merging**
