### PR TITLE
Add traverse function

### PR DESCRIPTION
**Pull request by willmurnane**
Adds a function which walks a tree of `PgNode` objects, calling a callback at each node. This is useful for things like the planner, where objects of a particular type could occur in many places, and those places change depending on the version of PostgreSQL that's being used. For example, `RTEKind_RTE_RESULT` is only defined and used in version 12+, so the planner would need to handle different layouts of plans depending on the version of PostgreSQL.

### CODE REVIEW

**Comment by thomcc** [comment]
Can you rebase this against `develop`/change the PR to be against that branch instead? We don't merge new features directly into master. (I could do it for you, but it may break your checkout)

**Comment by eeeebbbbrrrr** [comment]
Hi @willmurnane.  Are you still interested in this PR?  In general I think this looks okay, but it's got some conflicts with `build.rs` now.

**Comment by willmurnane** [comment]
Yes, I am. I’ll try to give it some TLC by early next week, thanks for the reminder.

**Comment by JelteF** [comment]
Instead of implementing this logic directly in pgx I think it would be better to call out to the existing walker functions that are already part of Postgres, like `query_tree_walker`, `expression_tree_walker` and `range_table_entry_walker`.

**Pull request closed without merging**
